### PR TITLE
Fix github action

### PR DESCRIPTION
**Pull request by msharr**
Github action for packaging stopped working recently. 

Errors I faced in a personal project:

1. [actions/upload-artifact@v1](https://github.com/actions/upload-artifact) - deprecated
2. `ModuleNotFoundError: No module named 'git'`
3. `Error: Could not get image config` - Fixes mentioned [here](https://github.com/guysoft/CustomPiOS/issues/236#issuecomment-2451424438)

Example runthrough: https://github.com/msharr/FullPageOS/actions/runs/11700553613/job/32584792883

### CODE REVIEW

**Comment by guysoft** [comment]
Working to fix it too

**Comment by msharr** [comment]
Couldn't quite get it to build: https://github.com/msharr/FullPageOS/actions/runs/11691391556

It worked on my private repo, but that's quite diverged so I'm not entirely sure what's causing it to fail

**Comment by msharr** [comment]
```
+ mkdir -p /opt/custompios/vnc
+ chown pi:pi /opt/custompios/vnc
+ '[' default '!=' default ']'
+ sudo -u pi /opt/custompios/scripts/setX11vncPass raspberry
sudo: unable to resolve host fv-az1110-518: Name or service not known
stored passwd in file: /home/pi/.vnc/passwd
+ sync
+ '[' '!' -f /opt/custompios/vnc/passwd ']'
+ echo '/opt/custompios/vnc/passwd was not created. Trying again.'
/opt/custompios/vnc/passwd was not created. Trying again.
+ sudo -u pi /opt/custompios/scripts/setX11vncPass raspberry
sudo: unable to resolve host fv-az1110-518: Name or service not known
stored passwd in file: /home/pi/.vnc/passwd
+ sync
+ '[' '!' -f /opt/custompios/vnc/passwd ']'
+ echo '/opt/custompios/vnc/passwd was not created again. Giving up.'
/opt/custompios/vnc/passwd was not created again. Giving up.
+ echo 'Failed to set a VNC password. Aborting build.'
Failed to set a VNC password. Aborting build.
+ exit 1
++++ echo_red 'build failed, unmounting image...'
++++ echo -e -n '\e[91m'
++++ echo build failed, unmounting image...
```

**Comment by msharr** [comment]
@guysoft I managed to get the build to succeed, but I made some changes beyond the scope of the Github action. 

https://github.com/msharr/FullPageOS/actions/runs/11700553613/job/32584792883

**Comment by guysoft** [comment]
I think I was just fixing the same thing, take a look at devel. Will update if it works here

**Comment by msharr** [comment]
Looks like you've gotten to a similar place to this PR. If you manage to fix it, you can go ahead and close this - I also wouldn't mind cleaning this one up if you prefer

**Comment by guysoft** [comment]
Thanks for your effort, helps me confirm stuff too.

**Pull request closed without merging**
