### PR TITLE
Make flags easier to maintain

### PR DESCRIPTION
**Pull request by ocitrev**
This is a suggestion for easier flag maintenance.
No new flags were added.

### CODE REVIEW

**Review by mikkelly-mi — COMMENTED** [review]
Clean code approach..

**Comment by guysoft** [comment]
Thanks for tiding up!

**Comment by ThomasKramps** [comment]
Why not also put the link --app=$(/home/pi/scripts/get_url) to the flags?

If you have a look into get_url, it is basically doing the same as --app=$(head -n 1 /boot/fullpageos.txt | sed -e "s/{serial}/${SERIAL}/g"), so the later one may be summarized to point to get_url as well.

**Comment by guysoft** [comment]
Because it makes sense to encapsulate the logic how to get the url from the script. It makes it easier to change the browser script, or change the way you get the url.

**Comment by ThomasKramps** [comment]
@ocitrev 

I don't know how to use github… Thank you :)

**Pull request merged**
