### PR TITLE
Hide cursor by default / add toggle script

### PR DESCRIPTION
**Pull request by hawkeyexp**
This will disable the cursor during image build and adds a simple script to change cursor show/hide via commandline and directly restarts lightdm service to reflect the change.

Hope all users will enjoy this optimization :-)

ps: wiki should be changed after merge :-)

### CODE REVIEW

**Comment by guysoft** [comment]
Is the cursor visible when the mouse is moved? 
The thing is that some people use FullPageOS as a kiosk, and disabling the cursor would break their kiosk. I am not sure we should have this on by default.

**Comment by hawkeyexp** [comment]
Hi, the cursor is fully hidden as it should be in a touch screen kiosk :-) I trid it with my rpi 7" orig touch display using home automation system and with cursor it was anoying - but for the special cases where a cursor is needed i added the script to toggle this option :-)

**Comment by guysoft** [comment]
I am still unsure I should merge this as a default option, it has a chance of breaking functionality. If I would have a way to get users to vote I would consider it, but it feels like something that would just create a bunch of new issues with the title "how do I get the cursor back?"

**Comment by hawkeyexp** [comment]
Make a partitial change - only add the script and change the docs - this will allow to switch via shell or mod the configs an boot to allow the user to trigger a show or hide for example.

**Comment by mrosu-sp** [comment]
Permanently hiding the cursor would be an issue to new users that want to use the FullPageDashboard.

This is because you have to use the GUI to make changes to the dashboard after the first setup.

**Comment by guysoft** [comment]
@hawkeyexp Of you only add the scirpt i'd merge it. You are welcome to make a new PR

**Pull request closed without merging**
