### PR TITLE
Created new script for moving mouse after page has been loaded.

### PR DESCRIPTION
**Pull request by slindgren**
I added new script that moves the mouse cursor 15 seconds after browser has been set to full screen. It might be a good idea to set few of these mouse move scripts, so if page refreshes or something. This is my first pull request, so there might be something wrong about it, but hopefully this helps.

### CODE REVIEW

**Comment by guysoft** [comment]
Did you test this?
The mouse move should probably go above, since chromium-browser is a blocking command to that 'while' loop

**Comment by slindgren** [comment]
Actually I didn't, I don't really know how to build the os.. :/

**Comment by guysoft** [comment]
You can modify the files directly on the filesystem and test. No need to
build it to test that kind of modification.

**Comment by slindgren** [comment]
Nice, I'll test it tonight and get back to you! :)

**Comment by slindgren** [comment]
There is something, but I'll try to fix it.. This is all so new to me, but lets not let that disturbe us ;)

**Comment by slindgren** [comment]
Now I've tested it.. It took time, but I got it working. Just adding the xdotool mousemove 9000 9000 to fullscreen -script moves the cursor to bottom right corner. Even in a bigger screen ;)

**Comment by guysoft** [comment]
Good, always test before making PR.
In the long run you would also want to squish those commits to one, so when someone examines it they can see only the final change, but I rather encourage contribution than be pedantic.

**Comment by tailorvj** [comment]
Very cool :) Congrats for our first Pull request commit

**Comment by slindgren** [comment]
Thanks :) I'm quite happy about it ^^

**Comment by guysoft** [comment]
Hey, I just tested and it does not work :-/

**Pull request merged**
