### PR TITLE
Make FullpageOS more secure

### PR DESCRIPTION
**Pull request by gbrakcounty**
As it is now, a kiosk mode window will open with the desired URL which is fine until a user presses CTRL+N or +M or CTRL+SHIFT+N or +M, a new standard Chromium window will open exposing the user to menu, which would allow some to change settings in chromium such as adding a proxy and redirecting other users to a malicious website.  This isn't really a kiosk since a new regular chromium window can be opened.  The Shortkeys extension no longer functions and chromium's built-in option to disable or modify keyboard shortcuts is extremely limited.  For example I can make New Window and New Incognito Window CTRL+SHIFT+N and +M respectively so that the standard shortcuts don't work.  But a malicious actor will probably know the other shortcuts or figure them out.  That is unacceptable for this use case.  Kiosks are supposed to be secure.  I know this isnt the fault of the developer but more on chromium itself.  But if you can find a way to redirect all keyboard shortcuts to a dead end and only allow some shortcuts like CTRL+W to close all windows/tabs and restart the browser (via your custom script), and ALT+left or right arrow to navigate.  Things like that are okay, but anything that exposes the settings menu is defeats the purpose.  

Again I'm not blaming you for this but I wanted to bring the issue to light.

### CODE REVIEW

**Comment by guysoft** [comment]
Hey, I think you PRed in to the wrong branch.
If you would like to fix that it would make the changes more readable.

I am already off to bed today.  But will take a look tomorrow.

I'm general I would want securing users from locally playing with a kiosk stand to be an optional feature.  Since for many users they want to option to open new windows. So I would support adding changes in to a variable, then building two variants.

**Comment by gbrakcounty** [comment]
> Hey, I think you PRed in to the wrong branch.
> If you would like to fix that it would make the changes more readable.
> 
> I am already off to bed today. But will take a look tomorrow.
> 
> I'm general I would want securing users from locally playing with a kiosk stand to be an optional feature. Since for many users want to option to open new windows, since they are using FullPageOS as a dashboard and not something served to potential malicious users. So I would support adding changes in to a variable, then building two variants.

Sorry I'm not familiar with how posting under Pull Requests works.  How would I go about fixing the post?

**Comment by guysoft** [comment]
So when you preform a "Pull Request" or PR (you might also see it as a "merge request". You are requesting someone to pull your changes from one branch to another.

You requested to merge in to a branch called "fullpageos" which is an old branch. so its showing as if you are adding A LOT of changes, like a few years of changes.

The "default branch" is what everyone is working on, you should send the Pull request to that.

To do so, you will need to create a new pull request, and select the "devel" branch of guysoft/FullPageOS. and your devel branch. Then the PR would show only the changes from the current version. It should create a new PR, and then we can close this one (and perhaps link to this one for the history, you will still be able to read this one).

**Comment by gbrakcounty** [comment]
Ok thanks.  Should I delete my long post?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gbrakcounty** [comment]
I was only trying to voice the issue.  I will follow your instructions to post the requests to the proper branch and I will keep it short, simple, and clear.

**Comment by gbrakcounty** [comment]
Which of these would be my devel branch?  How would I find out?

***@***.***

**Comment by guysoft** [comment]
Ok, It seems like a misunderstanding.
You opened a pull request, which is a request stating you have new code to contribute to the project. So I didn't understand what you wanted exactly.

If you want to open an issue you should use the "issue" tab or this url:
https://github.com/guysoft/FullPageOS/issues

Closing this for now

**Pull request closed without merging**
