### PR TITLE
Added Github action to build image for tagged releases

### PR DESCRIPTION
**Pull request by bitbyt3r**
This adds the necessary config to build a raspberry pi image and create a github release for any push tagged with a version number.

### CODE REVIEW

**Comment by guysoft** [comment]
1. If I pull this, does this means FullPageOS gets builds on github? Should I do anything else?

**Comment by bitbyt3r** [comment]
If you merge this them github will build an image and attach it to the release every time you tag a commit with a version string. It should also be useful as a template for others to do the same (afaik without needing to change anything). If you don't want it to be active then I could drop the push trigger from it, though then people who want to use it will have to add it back.

**Comment by guysoft** [comment]
Also - this won't work on this repo because versions don't start with v

**Comment by guysoft** [comment]
Ok, lets try it

**Comment by bitbyt3r** [comment]
Weird, looks like we got unlucky with a mirror? https://github.com/guysoft/FullPageOS/runs/815514416?check_suite_focus=true

We'll see what the next one does in a couple minutes.

**Comment by guysoft** [comment]
Still fails, in the end we will build our own mirror.

**Comment by bitbyt3r** [comment]
That's very strange. You can try re-running the job without a new commit on the build page: https://github.com/guysoft/FullPageOS/runs/815540216?check_suite_focus=true

I'm not sure what to do about a bad mirror.

**Pull request merged**
